# Generated by Django 4.0.4 on 2023-03-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, null=True)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('action_id', models.IntegerField(blank=True, null=True)),
                ('share', models.BooleanField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
                ('totp_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('notification_type', models.CharField(max_length=100)),
                ('odoobot_state', models.CharField(blank=True, max_length=100, null=True)),
                ('odoobot_failed', models.BooleanField(blank=True, null=True)),
                ('target_sales_won', models.IntegerField(blank=True, null=True)),
                ('target_sales_done', models.IntegerField(blank=True, null=True)),
                ('target_sales_invoiced', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
