# Generated by Django 4.0.4 on 2023-03-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resusers',
            options={'managed': False},
        ),
    ]
